DROP DATABASE IF EXISTS battle_db;
DROP USER IF EXISTS admin;

CREATE USER admin
  WITH PASSWORD 'password'
       CONNECTION LIMIT -1
       NOSUPERUSER
       NOCREATEDB
       NOCREATEROLE
       NOREPLICATION;


CREATE DATABASE battle_db
  WITH OWNER admin
       ENCODING 'UTF8'
       TABLESPACE pg_default
       CONNECTION LIMIT -1
       LC_COLLATE 'en_US.UTF-8'
       LC_CTYPE 'en_US.UTF-8'
       TEMPLATE template0;
